{
 "title": "Matrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Spark Executor Jvm Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "SPARK_METRICS.*.driver.ExecutorMetrics.JVMHeapMemory"
    }
   ]
  },
  {
   "title": "Kafka Connect - Failure Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "KAFKA-CONNECT_METRICS.connect.kafka.connect.type_connector-task-metrics.connector_jdbc_source_mysql_20.task_0.offset-commit-failure-percentage"
    }
   ]
  },
  {
   "title": "Spark - Rows/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "SPARK_METRICS.*.driver.ETLJob.streaming.inputRowsPerSecond"
    }
   ]
  },
  {
   "title": "Kafka Connect - Batch Size Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "KAFKA-CONNECT_METRICS.connect.kafka.connect.type_connector-task-metrics.connector_jdbc_source_mysql_20.*.batch-size-max"
    }
   ]
  }
 ]
}